[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net"] }
tower-http = { version = "0.6", features = ["fs", "compression-gzip", "compression-br", "set-header"] }
tower = "0.5"
http = "1"

[profile.release]
lto = true
strip = true
codegen-units = 1
